### ISSUE TITLE
A component required a bean named 'kafkaListenerStringContainerFactory' that could not be found.

### ISSUE THREAD

**Issue by zakirovvadim** [junaidsahmed/spring-kafka-utility#1]
Hello, could you help me? I get the error with name "A component required a bean named 'kafkaListenerStringContainerFactory' that could not be found." or with kafkaListenerJSONContainerFactory, when I use only consumer, why does it happen?

**Comment by junaidsahmed** [comment]
what spring version, you're using? so if you're doing the same thing making and writing Kafka configs as a starter then for spring boot v3 you need to make some additional changes. Once you add the starter in spring it loads all the beans so if there is any issue with the starter then the necessary config beans will not be added and you will get the exception.
check this link to add changes according to Spring Boot 3
https://dzone.com/articles/spring-boot-3-creating-a-custom-starter

**Comment by zakirovvadim** [comment]
I use Spring 2.7.4 inside custom starter, but project which will use this starter has Spring boot 3+.

**Comment by junaidsahmed** [comment]
the bean creation error is coming. It seems to me that your spring boot v3 app is loading starter beans properly when you are calling the consumer function.  What I can suggest is better to use spring 3 for your starter if possible.

**Comment by zakirovvadim** [comment]
Generally, I have shorten the project, added some features like KafkaProperties and I have changed the spring.factories to org.springframework.boot.autoconfigure. AutoConfiguration.imports (with increasing the Spring Boot to 3.2.2), but, nothing changes. My screen, if it interesting:)
![image](https://github.com/junaidsahmed/spring-kafka-utility/assets/68819815/305a4672-9dff-457a-a41c-fda9d721e90f)
![image](https://github.com/junaidsahmed/spring-kafka-utility/assets/68819815/e9949a1f-2ecb-4f49-9823-336e6b87596f)
